

export const data = [
    {
        id: 'r25',
        name: 'Boolean Blog',
        image:'boolean-blog',
        gif: '',
        tool:'react',
        link:'https://boolean-blog.vercel.app/',
        source: 'https://github.com/emreozturanli/Boolean-Blog',
    },
    {
        id: 'r24',
        name: 'Contact App Firebase',
        image:'contact-app-firebase',
        gif: '',
        tool:'react',
        link:'https://contact-app-firebase.vercel.app/',
        source: 'https://github.com/emreozturanli/contact-app-firebase',
    },
    {
        id: 'r21',
        name: 'Movie App Firebase',
        image:'movie-app-firebase',
        gif: '',
        tool:'react',
        link:'https://movie-app-react-firebase.vercel.app/',
        source: 'https://github.com/emreozturanli/Movie-App-React-Firebase',
    },
    {
        id: 'r1',
        name: 'Recipe App',
        image:'recipe-app',
        gif: '',
        tool:'react',
        link:'https://recipe-app-react-routerv6.vercel.app/',
        source: 'https://github.com/emreozturanli/Task-Tracker-React-Axios',
    },
    {
        id: 'r23',
        name: 'Keeper App Firebase',
        image:'keeper-app',
        gif: '',
        tool:'react',
        link:'https://keeper-app-firebase.vercel.app/',
        source: 'https://github.com/emreozturanli/keeper-app-firebase',
    },
    {
        id: 'r2',
        name: 'Dukkan',
        image:'dukkan',
        gif: '',
        tool:'react',
        link:'https://dukkan-react.vercel.app/',
        source: 'https://github.com/emreozturanli/Task-Tracker-React-Axios',
    },
    {
        id: 'r3',
        name: 'Meals',
        image:'meals',
        gif: '',
        tool:'react',
        link:'https://meals-react-router.vercel.app/',
        source: 'https://github.com/emreozturanli/Task-Tracker-React-Axios',
    },
    {
        id: 'r4',
        name: 'Countries-React',
        image:'countries-react',
        gif: '',
        tool:'react',
        link:'https://countries-react-router.vercel.app/',
        source: 'https://github.com/emreozturanli/Task-Tracker-React-Axios',
    },
    {
        id: 'r5',
        name: 'Users',
        image:'users',
        gif: '',
        tool:'react',
        link:'https://users-react-router.vercel.app/',
        source: 'https://github.com/emreozturanli/Task-Tracker-React-Axios',
    },
    {
        id: 'r6',
        name: 'Task Tracker Axios',
        image:'task-tracker-axios',
        gif: '',
        tool:'react',
        link:'https://task-tracker-react-axios.vercel.app/',
        source: 'https://github.com/emreozturanli/Task-Tracker-React-Axios',
    },
    {
        id: 'r7',
        name: 'Task Tracker',
        image:'task-tracker',
        gif: '',
        tool:'react',
        link:'https://task-tracker-react-lime.vercel.app/',
        source: 'https://github.com/emreozturanli/Task-Tracker-React',
    },
    {
        id: 'r8',
        name: 'Weather Forecast',
        image:'weather-forecast',
        gif: '',
        tool:'react',
        link:'https://weather-forecast-api-react.vercel.app/',
        source: 'https://github.com/emreozturanli/Weather-Forecast-React',
    },
    {
        id: 'r9',
        name: 'Cinetallinn',
        image:'cinetallinn',
        gif: '',
        tool:'react',
        link:'https://cine-tallinn-react.vercel.app/',
        source: 'https://github.com/emreozturanli/CineTallinn-React',
    },
    {
        id: 'r10',
        name: 'Languages',
        image:'languages',
        gif: '',
        tool:'react',
        link:'https://github.com/emreozturanli/Languages-React',
        source: 'https://emreozturanli.github.io/Languages-React/',
    },
    {
        id: 'r11',
        name: 'To-Do React',
        image:'to-do-react',
        gif: '',
        tool:'react',
        link:'https://to-do-app-w-react.vercel.app/',
        source: 'https://github.com/emreozturanli/To-Do-App-React',
    },
    {
        id: 'r12',
        name: 'Shopping List',
        image:'shopping-list',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Shopping-List/',
        source: 'https://github.com/emreozturanli/Shopping-List',
    },
    {
        id: 'r13',
        name: 'Navbar',
        image:'navbar',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Navbar-React/',
        source: 'https://github.com/emreozturanli/Navbar-React',
    },
    {
        id: 'r14',
        name: 'Tour Places',
        image:'tour-places',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Tour-Places/',
        source: 'https://github.com/emreozturanli/Tour-Places',
    },
    {
        id: 'r15',
        name: 'Tabs',
        image:'tabs',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Tabs-React/',
        source: 'https://github.com/emreozturanli/Tabs-React',
    },
    {
        id: 'r16',
        name: 'Color Generator',
        image:'color-generator',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Color-Generator-React/',
        source: 'https://github.com/emreozturanli/Color-Generator-React',
    },
    {
        id: 'r17',
        name: 'Slider',
        image:'slider',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Slider-React/',
        source: 'https://github.com/emreozturanli/Slider-React',
    },
    {
        id: 'r18',
        name: 'Menu',
        image:'menu',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Menu-React/',
        source: 'https://github.com/emreozturanli/Menu-React',
    },
    {
        id: 'r19',
        name: 'Accordion',
        image:'accordion',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Accordion-React/',
        source: 'https://github.com/emreozturanli/Accordion-React',
    },
    {
        id: 'r20',
        name: 'Tours',
        image:'tours',
        gif: '',
        tool:'react',
        link:'https://emreozturanli.github.io/Tours-React/',
        source: 'https://github.com/emreozturanli/Tours-React',
    },
    {
        id: 'r22',
        name: 'Random User',
        image:'random-user',
        gif: '',
        tool:'react',
        link:'https://random-user-react-mindset.vercel.app/',
        source: 'https://github.com/emreozturanli/Random-User-React',
    },
    {
        id: 'j1',
        name: 'To-Do App',
        image:'to-do-app',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/To-Do-App-With-JS/',
        source: 'https://github.com/emreozturanli/To-Do-App-With-JS',
    },
    {
        id: 'j2',
        name: 'Countries',
        image:'countries',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/Countries/',
        source: 'https://github.com/emreozturanli/Countries',
    },
    {
        id: 'j3',
        name: 'Calculator',
        image:'calculator',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/Calculator-HTML-CSS-JS/',
        source: 'https://github.com/emreozturanli/Calculator-HTML-CSS-JS',
    },
    {
        id: 'j4',
        name: 'Guess the Number',
        image:'guess-the-number',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/Guess-the-Number/',
        source: 'https://github.com/emreozturanli/Guess-the-Number',
    },
    {
        id: 'j5',
        name: 'Learn JS DOM',
        image:'learn-js-dom',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/Learn-Javascript-DOM/',
        source: 'https://github.com/emreozturanli/Learn-Javascript-DOM',
    },
    {
        id: 'j6',
        name: 'Checkout',
        image:'checkout',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/Checkout-Form/',
        source: 'https://github.com/emreozturanli/Checkout-Form',
    },
    {
        id: 'j7',
        name: "Kids' Zoo",
        image:'kids-zoo',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/Kids-Zoo/',
        source: 'https://github.com/emreozturanli/Kids-Zoo',
    },
    {
        id: 'j8',
        name: 'Simon Game',
        image:'simon-game',
        gif: '',
        tool:'javascript',
        link:'https://emreozturanli.github.io/Simon-Game/',
        source: 'https://github.com/emreozturanli/Simon-Game',
    },
    {
        id: 'c1',
        name: 'Day-n-Nite',
        image:'day-n-nite',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Day-n-Nite/',
        source: 'https://github.com/emreozturanli/Day-n-Nite',
    },
    {
        id: 'c2',
        name: 'Portfolio Template -2',
        image:'portfolio-website-template-2',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Portfolio-Website-Template-2/',
        source: 'https://github.com/emreozturanli/Portfolio-Website-Template-2',
    },
    {
        id: 'c3',
        name: 'Portfolio Template',
        image:'portfolio-website-template',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Portfolio-Website-Template/',
        source: 'https://github.com/emreozturanli/Portfolio-Website-Template',
    },
    {
        id: 'c4',
        name: 'Netflix Survey Form',
        image:'netflix',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Netflix-Survey-Form/',
        source: 'https://github.com/emreozturanli/Netflix-Survey-Form',
    },
    {
        id: 'c5',
        name: 'Portfolio SCSS',
        image:'portfolio-scss',
        gif: '',
        tool:'css',
        link:'',
        source: 'https://github.com/emreozturanli/Portfolio-Website-With-SCSS',
    },
    {
        id: 'c6',
        name: 'Studeo',
        image:'studeo',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/STUDEO-Full-Bootstrap-Web-Site/',
        source: 'https://github.com/emreozturanli/STUDEO-Full-Bootstrap-Web-Site',
    },
    {
        id: 'c7',
        name: 'Parallax Website',
        image:'parallax',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Parallax-Website/',
        source: 'https://github.com/emreozturanli/Parallax-Website',
    },
    {
        id: 'c8',
        name: 'Helicopter Animation',
        image:'helicopter-animation',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Helicopter-Animation/',
        source: 'https://github.com/emreozturanli/Helicopter-Animation',
    },
    {
        id: 'c9',
        name: 'Google',
        image:'google',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Google-Landing-Page/',
        source: 'https://github.com/emreozturanli/Google-Landing-Page',
    },
    {
        id: 'c10',
        name: 'Form Exercise',
        image:'form-exercise',
        gif: '',
        tool:'css',
        link:'https://emreozturanli.github.io/Form-Exercise/',
        source: 'https://github.com/emreozturanli/Form-Exercise',
    },
] 